[package]
name = "yt-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.7"
inquire = "0.6.2"
rustube = { version = "0.6.0", features = ["blocking", "callback"] }
